-- ============================================================================
-- Migration 038: Athlete Intelligence Briefs (AIB)
-- Phase 2 of Enterprise Migration
--
-- AIBs are pre-synthesized coaching summaries generated by Haiku ($0.003/gen).
-- They replace the need for agents to interpret 90+ raw snapshot fields.
--
-- Triggers: snapshot change + lazy fallback (stale >24h)
-- ============================================================================

-- ── Table ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS athlete_intelligence_briefs (
    id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    athlete_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- The brief itself
    summary_text    TEXT NOT NULL,
    snapshot_hash   TEXT NOT NULL,          -- MD5 hash of key snapshot fields (change detection)

    -- Context at generation time (for debugging/auditing)
    sport           TEXT,
    position        TEXT,
    age_band        TEXT,
    readiness_score TEXT,                   -- Green | Yellow | Red at gen time
    acwr            NUMERIC(5,2),
    injury_risk_flag TEXT,                  -- GREEN | AMBER | RED at gen time

    -- Generation metadata
    model_used      TEXT NOT NULL DEFAULT 'claude-3-5-haiku-20241022',
    cost_usd        NUMERIC(6,4) NOT NULL DEFAULT 0.003,
    is_current      BOOLEAN NOT NULL DEFAULT true,
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Timestamps
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ────────────────────────────────────────────────────────────────

-- Fast lookup: current brief for athlete (used by context_assembly_node)
CREATE INDEX IF NOT EXISTS idx_aib_athlete_current
    ON athlete_intelligence_briefs (athlete_id, is_current)
    WHERE is_current = true;

-- Staleness check: find briefs older than threshold
CREATE INDEX IF NOT EXISTS idx_aib_generated_at
    ON athlete_intelligence_briefs (generated_at DESC);

-- Hash lookup: detect if snapshot changed since last AIB
CREATE INDEX IF NOT EXISTS idx_aib_snapshot_hash
    ON athlete_intelligence_briefs (athlete_id, snapshot_hash);

-- ── RLS ────────────────────────────────────────────────────────────────────

ALTER TABLE athlete_intelligence_briefs ENABLE ROW LEVEL SECURITY;

-- Athletes can read their own briefs
CREATE POLICY "Athletes can read own AIBs"
    ON athlete_intelligence_briefs
    FOR SELECT
    USING (athlete_id = auth.uid());

-- Service role has full access (for Python AI service writes)
CREATE POLICY "Service role full access to AIBs"
    ON athlete_intelligence_briefs
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ── Comments ───────────────────────────────────────────────────────────────

COMMENT ON TABLE athlete_intelligence_briefs IS
    'Pre-synthesized coaching intelligence briefs generated by Haiku. '
    'Replaces raw snapshot field interpretation in agent prompts. '
    'Phase 2 of enterprise migration.';

COMMENT ON COLUMN athlete_intelligence_briefs.snapshot_hash IS
    'MD5 hash of key snapshot fields. AIB regenerates when hash changes.';

COMMENT ON COLUMN athlete_intelligence_briefs.is_current IS
    'Only one brief per athlete should be current. Previous briefs kept for audit.';
