"""
Tomo AI Service — Response Card Models v2

Extends cards.py with the additional card types that the mobile app renders
but were missing Pydantic validation. This file adds 15 card types to bring
the total from 13 → 28 validated types.

The mobile app renders 47 total types (19 display + 28 capsules), but capsule
cards are generated by deterministic code (not LLM), so they don't need
LLM-output validation. The 28 types here cover all LLM-generated cards.

Usage: Import CARD_TYPE_MAP_V2 in format_response to validate every card
before streaming to mobile. Unknown types pass through with a warning.
"""

from __future__ import annotations

from typing import Optional, Any

from pydantic import BaseModel, Field

# Import all existing v1 models
from app.models.cards import (
    StatRowCard,
    StatGridCard,
    ScheduleListCard,
    ZoneStackCard,
    TextCard,
    CoachNoteCard,
    SessionPlanCard,
    ProgramRecommendationCard,
    DrillCard,
    BenchmarkBar,
    ClashListCard,
    PhvAssessmentCard,
    ConfirmCard,
    ActionChip,
    TomoResponse,
    CARD_TYPE_MAP,
)


# ── New Card Types (v2 additions) ─────────────────────────────────────

class WeekPlanDay(BaseModel):
    """Single day in a week plan."""
    day: str                                    # "MON", "TUE", etc.
    tags: list[dict[str, str]] = Field(default_factory=list)  # [{label, color}]
    note: Optional[str] = None
    time: Optional[str] = None                  # "5:30 PM" or "TBC"


class WeekPlanCard(BaseModel):
    """Colored pills per day — weekly overview."""
    type: str = "week_plan"
    title: Optional[str] = None
    date_range: Optional[str] = None            # "Apr 13-19"
    days: list[WeekPlanDay]


class WeekDaySchedule(BaseModel):
    """Single day in a week schedule."""
    date: str
    day: Optional[str] = None                   # "Monday"
    events: list[dict[str, Any]] = Field(default_factory=list)
    event_count: int = 0
    is_rest_day: bool = False


class WeekScheduleCard(BaseModel):
    """Multi-day schedule view."""
    type: str = "week_schedule"
    summary: Optional[str] = None
    schedule: list[WeekDaySchedule]


class ChoiceOption(BaseModel):
    """Single option in a choice card."""
    label: str
    description: Optional[str] = None
    value: str                                  # Message sent back when tapped


class ChoiceCard(BaseModel):
    """Radio-style option picker."""
    type: str = "choice_card"
    headline: str
    options: list[ChoiceOption]


class InjuryCard(BaseModel):
    """Injury status display."""
    type: str = "injury_card"
    location: str
    severity: int = Field(ge=1, le=3)           # 1=soreness, 2=pain, 3=cannot train
    severity_label: Optional[str] = None
    logged_at: Optional[str] = None
    recovery_tip: Optional[str] = None
    auto_adjusted_session: Optional[str] = None


class GoalCard(BaseModel):
    """Goal progress tracking."""
    type: str = "goal_card"
    title: str
    target_value: Optional[float] = None
    target_unit: Optional[str] = None
    current_value: Optional[float] = None
    progress_pct: Optional[float] = None
    deadline: Optional[str] = None
    days_remaining: Optional[int] = None
    trend: Optional[str] = None                 # "improving" | "stable" | "declining"


class DailyBriefingCard(BaseModel):
    """Daily summary card."""
    type: str = "daily_briefing_card"
    date: Optional[str] = None
    readiness_color: Optional[str] = None       # "green" | "yellow" | "red"
    readiness_score: Optional[int] = None
    acwr: Optional[float] = None
    load_zone: Optional[str] = None
    event_count: Optional[int] = None
    training_count: Optional[int] = None
    match_count: Optional[int] = None
    urgent_goals: list[str] = Field(default_factory=list)
    pending_journal_count: Optional[int] = None
    briefing_summary: Optional[str] = None


class SchedulePreviewEvent(BaseModel):
    """Single event in a schedule preview."""
    name: str
    date: Optional[str] = None
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    event_type: Optional[str] = None
    intensity: Optional[str] = None
    violations: list[str] = Field(default_factory=list)
    alternatives: list[dict[str, Any]] = Field(default_factory=list)


class SchedulePreviewCard(BaseModel):
    """Event batch preview with conflict analysis."""
    type: str = "schedule_preview"
    events: list[SchedulePreviewEvent]
    summary: Optional[str] = None
    scenario: Optional[str] = None
    confirm_action: Optional[str] = None
    confirm_payload: Optional[dict[str, Any]] = None


# ── v2 Card Type Registry (extends v1) ────────────────────────────────

CARD_TYPE_MAP_V2: dict[str, type[BaseModel]] = {
    # All v1 types
    **CARD_TYPE_MAP,
    # v2 additions
    "week_plan": WeekPlanCard,
    "week_schedule": WeekScheduleCard,
    "choice_card": ChoiceCard,
    "injury_card": InjuryCard,
    "goal_card": GoalCard,
    "daily_briefing_card": DailyBriefingCard,
    "schedule_preview": SchedulePreviewCard,
}


# ── Validation Helper ─────────────────────────────────────────────────

def validate_card(card_dict: dict[str, Any]) -> tuple[bool, Optional[dict[str, Any]], Optional[str]]:
    """
    Validate a card against the Pydantic registry.

    Args:
        card_dict: Raw card dict from LLM output

    Returns:
        (valid, cleaned_card_or_None, error_message_or_None)
        - Unknown types pass through as valid (forward compatibility)
        - Known types are validated and cleaned
        - Invalid known types return (False, None, error_description)
    """
    card_type = card_dict.get("type")
    if not card_type:
        return False, None, "Card missing 'type' field"

    model_cls = CARD_TYPE_MAP_V2.get(card_type)
    if not model_cls:
        # Unknown type — pass through with warning (forward compat for capsules)
        return True, card_dict, None

    try:
        validated = model_cls.model_validate(card_dict)
        # by_alias=True ensures fields with aliases (e.g., event_type→type) use
        # the alias name in output, matching what the mobile app expects.
        return True, validated.model_dump(by_alias=True, exclude_none=True), None
    except Exception as e:
        return False, None, f"{card_type}: {str(e)[:200]}"


def validate_response(response_dict: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    """
    Validate a full TomoResponse, cleaning each card.

    Returns:
        (cleaned_response, list_of_warnings)
    """
    warnings: list[str] = []
    cleaned_cards: list[dict[str, Any]] = []

    for card in response_dict.get("cards", []):
        valid, cleaned, error = validate_card(card)
        if valid and cleaned:
            cleaned_cards.append(cleaned)
        elif error:
            warnings.append(error)

    response_dict["cards"] = cleaned_cards
    return response_dict, warnings
