/**
 * POST /api/v1/admin/enterprise/protocols/generate
 *
 * Accepts a PD's plain-text prompt (plus optional scope hints) and returns
 * a structured protocol draft generated by Claude Sonnet 4. The draft is
 * NOT saved to pd_protocols — the caller reviews it and POSTs to the
 * existing /api/v1/admin/enterprise/protocols/builder endpoint when ready.
 *
 * Auth: institutional_pd role minimum via requireEnterprise.
 * Rate limit: 10 generations per user per minute (in-memory, best-effort).
 * Response is 200 even for validation failures so the UI can surface
 * field-level errors inline; the caller uses the `validation_errors` shape
 * to decide whether to render a review form or a retry prompt.
 */

import { NextRequest, NextResponse } from "next/server";
import { requireEnterprise } from "@/lib/admin/enterpriseAuth";
import { checkRateLimit } from "@/lib/rateLimit";
import {
  generateProtocolDraft,
} from "@/services/admin/pdProtocolGenerator";
import { GenerateRequestSchema } from "@/services/admin/pdProtocolDraftSchema";
import { logger } from "@/lib/logger";

const RATE_LIMIT_PER_MINUTE = 10;
const RATE_LIMIT_WINDOW_MS = 60_000;

export async function POST(req: NextRequest) {
  const auth = await requireEnterprise(req, "institutional_pd");
  if ("error" in auth) return auth.error;

  const { user } = auth;

  // Rate limit — protects the Anthropic bill from a misbehaving client.
  const rl = checkRateLimit(user.id, RATE_LIMIT_PER_MINUTE, RATE_LIMIT_WINDOW_MS);
  if (!rl.allowed) {
    return NextResponse.json(
      {
        error: "Rate limit exceeded — try again in a moment.",
        retry_after_ms: rl.resetAt - Date.now(),
      },
      { status: 429 },
    );
  }

  // Parse + validate the request body with the Zod schema that backs the UI.
  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = GenerateRequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      {
        error: "Invalid request",
        issues: parsed.error.issues.map((i) => ({
          path: i.path.join("."),
          message: i.message,
        })),
      },
      { status: 400 },
    );
  }

  const { prompt, scope_hints } = parsed.data;

  // Resolve tenant context. Super admins can author global protocols
  // (tenant_id = null). Institutional PDs fall through to their active
  // tenant cookie, then their primary membership.
  const activeTenant =
    req.cookies.get("cms_active_tenant")?.value ?? user.primaryTenantId;
  const tenantId = user.isSuperAdmin ? activeTenant ?? null : activeTenant;

  try {
    const result = await generateProtocolDraft({
      prompt,
      scopeHints: scope_hints,
      userId: user.id,
      userEmail: user.email,
      tenantId,
    });

    return NextResponse.json({
      generation_id: result.generation_id,
      protocol: result.draft,
      grounding_chunks: result.grounding_chunks,
      model: result.telemetry.model,
      cost_usd: result.telemetry.costUsd,
      latency_ms: result.telemetry.latencyMs,
      validation_errors: result.validation_errors,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Generation failed";
    logger.error("[protocols/generate] Generation failed", {
      userId: user.id,
      error: message,
    });
    return NextResponse.json(
      { error: message },
      { status: 500 },
    );
  }
}
