/**
 * Chat Pills — Default library + config.
 *
 * This is the single source of truth for the seed and the GET fallback.
 * The migration references it via a JSON copy (migration copies the JSON
 * inline because SQL can't import TS), so if you edit this file you must
 * also keep the migration JSON in sync. A later PR may switch to a seed
 * script that generates the migration from this constant.
 */

import type { ChatPillsConfig } from "./types";

export const DEFAULT_CHAT_PILLS_CONFIG: ChatPillsConfig = {
  version: 1,
  emptyState: {
    mode: "fixed",
    fixedIds: ["plan_study", "plan_training", "plan_my_week", "check_benchmarks"],
    defaultFallbackIds: [
      "plan_study",
      "plan_training",
      "plan_my_week",
      "check_benchmarks",
    ],
  },
  inResponse: {
    enabled: false,
    maxPerResponse: 3,
    shadowMode: false,
  },
  library: [
    {
      id: "plan_study",
      label: "Study",
      message: "plan my study schedule",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["exam_soon", "schedule_gap", "response:text"],
      excludeTags: [],
      priority: 6,
    },
    {
      id: "plan_training",
      label: "Train",
      message: "plan my training week",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["empty_week", "schedule_gap", "has_programs", "response:session_plan"],
      excludeTags: ["rest_day", "injury"],
      priority: 6,
    },
    {
      id: "plan_my_week",
      label: "Plan My Week",
      message: "help me plan my week",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["empty_week", "schedule_gap", "always"],
      excludeTags: [],
      priority: 4,
    },
    {
      id: "check_benchmarks",
      label: "My Benchmarks",
      message: "show me my benchmarks",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["has_benchmarks", "response:benchmark", "always"],
      excludeTags: [],
      priority: 5,
    },
    {
      id: "log_test",
      label: "Log a test",
      message: "I want to log a new test",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["metric_missing", "response:benchmark"],
      excludeTags: [],
      priority: 7,
    },
    {
      id: "check_in",
      label: "Check in",
      message: "check in",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["needs_checkin", "stale_checkin"],
      excludeTags: [],
      priority: 9,
    },
    {
      id: "add_event",
      label: "Add event",
      message: "I want to add a training session",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["empty_week", "rest_day"],
      excludeTags: [],
      priority: 5,
    },
    {
      id: "strengths_gaps",
      label: "My strengths",
      message: "what are my strengths and gaps?",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["has_benchmarks", "benchmark_weak", "benchmark_strong"],
      excludeTags: [],
      priority: 6,
    },
    {
      id: "leaderboard",
      label: "Leaderboard",
      message: "show me the leaderboard",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: false,
      tags: ["has_benchmarks", "always"],
      excludeTags: [],
      priority: 3,
    },
    {
      id: "my_rules",
      label: "My rules",
      message: "edit my schedule rules",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["has_clash", "schedule_gap"],
      excludeTags: [],
      priority: 5,
    },
    {
      id: "check_conflicts",
      label: "Check conflicts",
      message: "check for any schedule conflicts",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["has_clash", "response:clash_fix"],
      excludeTags: [],
      priority: 8,
    },
    {
      id: "my_programs",
      label: "My programs",
      message: "my programs",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["has_programs", "no_programs", "response:programs"],
      excludeTags: [],
      priority: 5,
    },
    {
      id: "growth_stage",
      label: "Growth stage",
      message: "calculate my growth stage",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: false,
      tags: ["growth", "cv_incomplete"],
      excludeTags: [],
      priority: 4,
    },
    {
      id: "notification_settings",
      label: "Notifications",
      message: "notification settings",
      enabled: true,
      allowInEmptyState: false,
      allowInResponse: false,
      tags: ["always"],
      excludeTags: [],
      priority: 2,
    },
    {
      id: "my_readiness",
      label: "My readiness",
      message: "what's my readiness?",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["response:readiness", "needs_checkin", "always"],
      excludeTags: [],
      priority: 6,
    },
    {
      id: "my_streak",
      label: "My streak",
      message: "my streak",
      enabled: true,
      allowInEmptyState: false,
      allowInResponse: true,
      tags: ["streak_milestone", "streak_risk"],
      excludeTags: [],
      priority: 5,
    },
    {
      id: "edit_cv",
      label: "Edit CV",
      message: "edit my CV profile",
      enabled: true,
      allowInEmptyState: false,
      allowInResponse: true,
      tags: ["cv_incomplete"],
      excludeTags: [],
      priority: 4,
    },
    {
      id: "my_timeline",
      label: "My timeline",
      message: "help me manage my timeline",
      enabled: true,
      allowInEmptyState: true,
      allowInResponse: true,
      tags: ["empty_week", "schedule_gap"],
      excludeTags: [],
      priority: 4,
    },
  ],
};
