import type { HubState } from "./types";

export const HUB_DEFAULTS: HubState = {
  dataGroups: [
    {
      id: "training_load",
      name: "Training load",
      description: "How hard the athlete has been training this week versus their normal baseline over the past month.",
      enabled: true,
      isDefault: true,
      fields: [
        { id: "atl", name: "This week's training load", fieldType: "number", scale: "live", enabled: true },
        { id: "ctl", name: "4-week average load", fieldType: "number", scale: "long_term", enabled: true },
        { id: "acwr", name: "Load spike % vs average", fieldType: "calculated", scale: "live", enabled: true },
        { id: "rest_days", name: "Days since last rest day", fieldType: "number", scale: "short_term", enabled: true },
      ],
    },
    {
      id: "daily_readiness",
      name: "Daily readiness",
      description: "How ready the athlete is to train today, based on sleep, energy, and how their body feels this morning.",
      enabled: true,
      isDefault: true,
      fields: [
        { id: "sleep_duration", name: "Sleep duration last night", fieldType: "number", scale: "live", enabled: true },
        { id: "sleep_quality", name: "Sleep quality (self-reported)", fieldType: "scale_1_10", scale: "live", enabled: true },
        { id: "hrv", name: "Morning recovery reading", fieldType: "number", scale: "live", enabled: true },
        { id: "wellness", name: "Wellness score", fieldType: "scale_1_10", scale: "live", enabled: true },
        { id: "rag", name: "Overall readiness signal", fieldType: "rag", scale: "live", enabled: true },
      ],
    },
    {
      id: "development_stage",
      name: "Physical development stage",
      description: "Where the athlete is in their physical maturation — critical for young athletes whose bodies are still growing.",
      enabled: true,
      isDefault: true,
      fields: [
        { id: "phv_stage", name: "Growth phase stage", fieldType: "text", scale: "long_term", enabled: true },
        { id: "phv_offset", name: "Growth phase offset (years)", fieldType: "number", scale: "long_term", enabled: true },
        { id: "phv_mult", name: "Load multiplier for this stage", fieldType: "number", scale: "long_term", enabled: true },
      ],
    },
    {
      id: "benchmarks",
      name: "Performance benchmarks",
      description: "How the athlete's test scores compare to the expected standards for their age, sport, and position.",
      enabled: true,
      isDefault: true,
      fields: [
        { id: "bench_gaps", name: "Qualities below target", fieldType: "text", scale: "long_term", enabled: true },
        { id: "bench_strengths", name: "Qualities above target", fieldType: "text", scale: "long_term", enabled: true },
        { id: "bench_priority", name: "Top development priority", fieldType: "text", scale: "short_term", enabled: true },
      ],
    },
    {
      id: "wellness_mental",
      name: "Wellness and mental load",
      description: "Emotional wellbeing, stress levels, and academic pressure — all affect how the body responds to training.",
      enabled: true,
      isDefault: true,
      fields: [
        { id: "wellness_7d", name: "7-day wellness average", fieldType: "number", scale: "short_term", enabled: true },
        { id: "wellness_trend", name: "Wellness trend direction", fieldType: "text", scale: "short_term", enabled: true },
        { id: "dual_load", name: "Combined stress index", fieldType: "number", scale: "live", enabled: true },
        { id: "injury_risk", name: "Injury risk level", fieldType: "rag", scale: "live", enabled: true },
      ],
    },
    {
      id: "injury_imbalances",
      name: "Injury and physical imbalances",
      description: "Current injuries, chronic issues, and physical imbalances like flat foot or hip asymmetry that affect what training is safe.",
      enabled: false,
      isDefault: false,
      fields: [],
    },
  ],

  guardrailRules: [
    {
      id: "load_red",
      when: "Training load this week is more than 50% higher than the 4-week average",
      condition: { field: "acwr", operator: "greater_than", value: 1.5 },
      action: "hard_stop",
      actionText: "Block all high-intensity sessions. Only allow active recovery.",
      sourceGroup: "training_load",
      enabled: true,
    },
    {
      id: "load_amber",
      when: "Training load this week is more than 30% higher than the 4-week average",
      condition: { field: "acwr", operator: "greater_than", value: 1.3 },
      action: "soft_limit",
      actionText: "Reduce session intensity to 75% of planned load.",
      sourceGroup: "training_load",
      enabled: true,
    },
    {
      id: "growth_explosive",
      when: "Athlete is in rapid growth phase AND any explosive exercise is requested",
      condition: { field: "phv_stage", operator: "equals", value: "mid_phv" },
      action: "hard_stop",
      actionText: "Block the exercise. Offer the safe alternative from the exceptions list.",
      sourceGroup: "development_stage",
      enabled: true,
    },
    {
      id: "hrv_suppressed",
      when: "Morning recovery reading is more than 30% below the athlete's 7-day personal average",
      condition: { field: "hrv", operator: "less_than", value: 0.7 },
      action: "soft_limit",
      actionText: "Cap session intensity at 60% of planned load. Add recovery guidance.",
      sourceGroup: "daily_readiness",
      enabled: true,
    },
    {
      id: "dual_load_high",
      when: "Combined training and school stress index is above 75%",
      condition: { field: "dual_load", operator: "greater_than", value: 75 },
      action: "soft_limit",
      actionText: "Cap athletic load at 75%. Add academic balance note to response.",
      sourceGroup: "wellness_mental",
      enabled: true,
    },
    {
      id: "red_readiness",
      when: "Overall readiness signal is Red",
      condition: { field: "rag", operator: "equals", value: "red" },
      action: "soft_limit",
      actionText: "Recommend rest or active recovery only. Do not suggest training sessions.",
      sourceGroup: "daily_readiness",
      enabled: true,
    },
  ],

  responseRules: [
    {
      id: "explain_reason",
      when: "When giving any training recommendation",
      instruction: "Always explain the physical reason behind the recommendation in one plain sentence. Example: \"We are focusing on aerobic work today because your body recovers better from this type of effort right now.\"",
      enabled: true,
    },
    {
      id: "benchmark_gap",
      when: "When an athlete's test score is below the target for their age and position",
      instruction: "Include a specific development suggestion targeting that quality. Name the gap. Example: \"Your sprint acceleration is below the standard for your age — here is a session focused on exactly that.\"",
      enabled: true,
    },
    {
      id: "growth_positive",
      when: "When an athlete is in their rapid growth phase",
      instruction: "Always frame any restrictions positively. Never use medical language. Focus on what the athlete CAN do. Example: \"Your body is doing important work right now — here is what works best for you today.\"",
      enabled: true,
    },
    {
      id: "no_dead_ends",
      when: "When the AI cannot recommend a planned exercise or session",
      instruction: "Always offer an alternative. Never leave the athlete with nothing to do. A short mobility session is better than no answer.",
      enabled: true,
    },
  ],

  contextBlocks: [
    {
      id: "sport_position",
      name: "Sport and position context",
      description: "The AI knows the demands of this athlete's sport and position and coaches accordingly.",
      enabled: true,
      locked: true,
    },
    {
      id: "growth_science",
      name: "Growth phase science",
      description: "The AI applies appropriate load and exercise limits based on the athlete's biological maturation stage.",
      enabled: true,
      locked: false,
    },
    {
      id: "adaptation_profile",
      name: "Individual adaptation profile",
      description: "The AI adjusts its approach based on how this specific athlete has historically responded to training.",
      enabled: true,
      locked: false,
    },
    {
      id: "readiness_science",
      name: "Daily readiness and recovery",
      description: "The AI factors in sleep quality, recovery trends, and wellness patterns when recommending session intensity.",
      enabled: true,
      locked: false,
    },
    {
      id: "active_recs",
      name: "Recent coaching recommendations",
      description: "The AI references what it suggested in the last 24 hours for continuity of guidance.",
      enabled: true,
      locked: false,
    },
    {
      id: "academic_stress",
      name: "Academic and life stress",
      description: "The AI adjusts training intensity around exam periods, travel, and high-stress weeks.",
      enabled: true,
      locked: false,
    },
  ],

  safetyFilters: [
    {
      id: "max_effort_growth",
      catches: "Maximum effort, 100%, go all out — for any athlete in rapid growth phase",
      action: "translate_plain_language",
      replacement: "Strong effort or high effort. Add a pacing note.",
      scope: "growth_phase",
      enabled: true,
      isDefault: true,
    },
    {
      id: "blocked_exercises",
      catches: "Barbell back squat, depth jumps, drop jumps, Olympic lifts, heavy deadlifts, loaded plyometrics",
      action: "remove_and_replace",
      replacement: "Insert the safe alternative. Briefly explain the substitution.",
      scope: "growth_phase",
      enabled: true,
      isDefault: true,
    },
    {
      id: "no_diagnosis",
      catches: "You have [condition], this is [injury], you are injured, this indicates [medical term]",
      action: "translate_plain_language",
      replacement: "Suggest: \"This might be worth checking with a physio.\"",
      scope: "always",
      enabled: true,
      isDefault: true,
    },
    {
      id: "no_acronyms_u16",
      catches: "Technical acronyms used without explanation for younger athletes",
      action: "translate_plain_language",
      replacement: "Use plain English equivalents from the language guide.",
      scope: "under_16",
      enabled: true,
      isDefault: true,
    },
  ],
};
