-- ============================================================================
-- Migration 015: Athlete Recommendations — Layer 4 of the Athlete Data Fabric
-- Pre-computed recommendation records generated by the Recommendation
-- Intelligence Engine (RIE) after every snapshot write.
-- ============================================================================

-- Core recommendations table
CREATE TABLE public.athlete_recommendations (
  rec_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  athlete_id          UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  rec_type            TEXT NOT NULL CHECK (rec_type IN (
                        'READINESS', 'LOAD_WARNING', 'RECOVERY', 'DEVELOPMENT',
                        'ACADEMIC', 'CV_OPPORTUNITY', 'TRIANGLE_ALERT', 'MOTIVATION'
                      )),
  priority            INT NOT NULL CHECK (priority BETWEEN 1 AND 4),
  status              TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN (
                        'PENDING', 'DELIVERED', 'ACTED', 'DISMISSED', 'EXPIRED', 'SUPERSEDED'
                      )),
  title               TEXT NOT NULL,
  body_short          TEXT NOT NULL,
  body_long           TEXT,
  confidence_score    DECIMAL(3,2) CHECK (confidence_score BETWEEN 0.00 AND 1.00),
  evidence_basis      JSONB NOT NULL DEFAULT '{}',
  trigger_event_id    UUID REFERENCES public.athlete_events(event_id) ON DELETE SET NULL,
  context             JSONB NOT NULL DEFAULT '{}',
  visible_to_athlete  BOOLEAN NOT NULL DEFAULT true,
  visible_to_coach    BOOLEAN NOT NULL DEFAULT true,
  visible_to_parent   BOOLEAN NOT NULL DEFAULT true,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at          TIMESTAMPTZ,
  acted_at            TIMESTAMPTZ
);

-- Row-level security
ALTER TABLE public.athlete_recommendations ENABLE ROW LEVEL SECURITY;

-- Athletes read own visible recommendations
CREATE POLICY "Athletes read own recommendations"
  ON public.athlete_recommendations FOR SELECT
  USING (athlete_id = auth.uid() AND visible_to_athlete = true);

-- Coaches read linked athlete recommendations
CREATE POLICY "Coaches read linked athlete recommendations"
  ON public.athlete_recommendations FOR SELECT
  USING (
    visible_to_coach = true
    AND EXISTS (
      SELECT 1 FROM public.relationships
      WHERE guardian_id = auth.uid()
        AND player_id = public.athlete_recommendations.athlete_id
        AND status = 'accepted'
    )
  );

-- Parents read linked athlete recommendations
CREATE POLICY "Parents read linked athlete recommendations"
  ON public.athlete_recommendations FOR SELECT
  USING (
    visible_to_parent = true
    AND EXISTS (
      SELECT 1 FROM public.relationships
      WHERE guardian_id = auth.uid()
        AND player_id = public.athlete_recommendations.athlete_id
        AND status = 'accepted'
    )
  );

-- Primary query path: active recs for an athlete, sorted by urgency
CREATE INDEX idx_recs_athlete_status_priority
  ON public.athlete_recommendations (athlete_id, status, priority);

-- Supersede logic: find existing pending recs of same type
CREATE INDEX idx_recs_athlete_type_status
  ON public.athlete_recommendations (athlete_id, rec_type, status);

-- Expiry cron: find pending recs past their expires_at
CREATE INDEX idx_recs_expires_pending
  ON public.athlete_recommendations (expires_at)
  WHERE status = 'PENDING';

-- Bulk time-range queries — BRIN for append-only
CREATE INDEX idx_recs_created_brin
  ON public.athlete_recommendations USING brin(created_at);

-- Only service role (RIE engine) writes recommendations
GRANT ALL ON public.athlete_recommendations TO service_role;


-- ============================================================================
-- Recommendation Delivery Log — tracks how/when recs are shown and interacted with
-- ============================================================================

CREATE TABLE public.rec_delivery_log (
  log_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  rec_id          UUID NOT NULL REFERENCES public.athlete_recommendations(rec_id) ON DELETE CASCADE,
  delivered_via   TEXT NOT NULL CHECK (delivered_via IN ('CARD', 'TOMO_CHAT', 'PUSH', 'COACH_DASHBOARD')),
  delivered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  interaction     TEXT CHECK (interaction IN ('VIEWED', 'TAPPED', 'ACTED', 'DISMISSED')),
  interacted_at   TIMESTAMPTZ
);

-- Row-level security
ALTER TABLE public.rec_delivery_log ENABLE ROW LEVEL SECURITY;

-- Athletes can read delivery logs for their own recommendations
CREATE POLICY "Athletes read own delivery logs"
  ON public.rec_delivery_log FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.athlete_recommendations ar
      WHERE ar.rec_id = public.rec_delivery_log.rec_id
        AND ar.athlete_id = auth.uid()
    )
  );

-- Delivery log per recommendation, most recent first
CREATE INDEX idx_delivery_log_rec
  ON public.rec_delivery_log (rec_id, delivered_at DESC);

-- Only service role writes delivery logs
GRANT ALL ON public.rec_delivery_log TO service_role;
