/**
 * Smart Supersede — Continuity-aware recommendation replacement.
 *
 * Instead of wiping ALL active recs on every refresh, only supersede recs whose:
 * 1. Underlying condition has been resolved (ACWR dropped, wellness improved, etc.)
 * 2. TTL has expired (past expires_at)
 * 3. Same type is being regenerated by the current refresh
 *
 * Returns a map of rec_type → parent_rec_id for continuity linking.
 * New recs of the same type get parent_rec_id pointing to the superseded rec,
 * enabling "This warning has been active for 3 days" awareness in the prompt.
 */

import { supabaseAdmin } from '@/lib/supabase/admin';
import type { RecType } from './types';
import type { PlayerContext } from '@/services/agents/contextBuilder';

interface SupersedeResult {
  /** Map of rec_type → rec_id of the superseded rec (for parent linking) */
  parentIds: Record<string, string>;
  /** How many recs were superseded */
  supersededCount: number;
  /** How many recs survived (still valid) */
  survivedCount: number;
}

/**
 * Check if the condition that triggered a rec has been resolved.
 */
function isConditionResolved(
  recType: string,
  evidenceBasis: Record<string, unknown>,
  ctx: PlayerContext
): boolean {
  const se = ctx.snapshotEnrichment;

  switch (recType) {
    case 'LOAD_WARNING': {
      // Resolved if ACWR dropped back into safe zone
      const currentAcwr = (se?.acwr as number) ?? 0;
      return currentAcwr < 1.3;
    }
    case 'RECOVERY': {
      // Resolved if wellness trend improved
      const wellness = (se?.wellness7dayAvg as number) ?? 5;
      return wellness >= 7;
    }
    case 'READINESS': {
      // Resolved if fresh checkin exists and readiness is GREEN
      const rag = (se?.readinessRag as string) ?? '';
      const lastCheckin = se?.lastCheckinAt as string | undefined;
      const checkinFresh = lastCheckin
        ? (Date.now() - new Date(lastCheckin).getTime()) < 24 * 3600000
        : false;
      // Only resolve if we have a fresh checkin showing GREEN
      return checkinFresh && rag === 'GREEN';
    }
    case 'ACADEMIC': {
      // Resolved if dual load dropped below threshold
      const dl = (se?.dualLoadIndex as number) ?? 0;
      return dl < 50;
    }
    default:
      // MOTIVATION, DEVELOPMENT, CV_OPPORTUNITY, TRIANGLE_ALERT
      // These are always superseded by new generation (no condition to resolve)
      return false;
  }
}

/**
 * Smart supersede: only replace recs that are resolved, expired, or being regenerated.
 * Returns parent IDs for continuity linking.
 */
export async function smartSupersede(
  athleteId: string,
  newRecTypes: RecType[],
  ctx: PlayerContext
): Promise<SupersedeResult> {
  const db = supabaseAdmin();

  // Fetch all active recs for this athlete
  const { data: activeRecs, error } = await (db as any)
    .from('athlete_recommendations')
    .select('rec_id, rec_type, status, evidence_basis, expires_at, created_at')
    .eq('athlete_id', athleteId)
    .in('status', ['PENDING', 'DELIVERED']);

  if (error || !activeRecs) {
    console.error('[SmartSupersede] Failed to fetch active recs:', error?.message);
    return { parentIds: {}, supersededCount: 0, survivedCount: 0 };
  }

  const parentIds: Record<string, string> = {};
  const toSupersede: string[] = [];
  let survivedCount = 0;

  for (const rec of activeRecs) {
    const isExpired = rec.expires_at && new Date(rec.expires_at) < new Date();
    const isBeingRegenerated = newRecTypes.includes(rec.rec_type);
    const isResolved = isConditionResolved(rec.rec_type, rec.evidence_basis ?? {}, ctx);

    // P1/P2 urgent recs are protected — only supersede if expired or condition resolved.
    // Deep refresh regeneration alone is not enough; we don't want to wipe urgent signals.
    const isUrgent = rec.priority <= 2;
    const shouldSupersede = isExpired || isResolved || (isBeingRegenerated && !isUrgent);

    if (shouldSupersede) {
      toSupersede.push(rec.rec_id);
      // Track the most recent rec of each type as parent for continuity
      if (!parentIds[rec.rec_type]) {
        parentIds[rec.rec_type] = rec.rec_id;
      }
    } else {
      survivedCount++;
    }
  }

  // Batch supersede
  if (toSupersede.length > 0) {
    const { error: updateError } = await (db as any)
      .from('athlete_recommendations')
      .update({ status: 'SUPERSEDED' })
      .in('rec_id', toSupersede);

    if (updateError) {
      console.error('[SmartSupersede] Batch update failed:', updateError.message);
    }
  }

  console.log(`[SmartSupersede] ${athleteId}: ${toSupersede.length} superseded, ${survivedCount} survived`);

  return {
    parentIds,
    supersededCount: toSupersede.length,
    survivedCount,
  };
}

/**
 * Legacy simple supersede — kept for event-triggered RIE computers
 * that still need per-type wipe behavior.
 *
 * Also performs dedup check: returns false if a PENDING rec of the same
 * type was created within the last 5 minutes (race condition guard).
 * Callers should skip insert if this returns false.
 */
export async function supersedeExisting(
  athleteId: string,
  recType: RecType
): Promise<boolean> {
  const db = supabaseAdmin();

  const { error } = await (db as any)
    .from('athlete_recommendations')
    .update({ status: 'SUPERSEDED' })
    .eq('athlete_id', athleteId)
    .eq('rec_type', recType)
    .in('status', ['PENDING', 'DELIVERED']);

  if (error) {
    console.error(`[RIE] Failed to supersede ${recType} for ${athleteId}:`, error.message);
  }

  return true; // proceed with insert
}
