/**
 * Recommendation Intelligence Engine — Type Definitions
 *
 * Core types for Layer 4 of the Athlete Data Fabric.
 * Recommendation records are pre-computed after every snapshot write
 * and stored in athlete_recommendations for O(1) reads.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type RecType =
  | 'READINESS'
  | 'LOAD_WARNING'
  | 'RECOVERY'
  | 'DEVELOPMENT'
  | 'ACADEMIC'
  | 'CV_OPPORTUNITY'
  | 'TRIANGLE_ALERT'
  | 'MOTIVATION';

export type RecStatus =
  | 'PENDING'
  | 'DELIVERED'
  | 'ACTED'
  | 'DISMISSED'
  | 'EXPIRED'
  | 'SUPERSEDED';

/** 1 = urgent, 2 = today, 3 = this week, 4 = informational */
export type RecPriority = 1 | 2 | 3 | 4;

// ---------------------------------------------------------------------------
// Core Recommendation Record
// ---------------------------------------------------------------------------

export interface Recommendation {
  rec_id: string;
  athlete_id: string;
  rec_type: RecType;
  priority: RecPriority;
  status: RecStatus;
  title: string;
  body_short: string;
  body_long: string | null;
  confidence_score: number;
  evidence_basis: Record<string, unknown>;
  trigger_event_id: string | null;
  context: Record<string, unknown>;
  visible_to_athlete: boolean;
  visible_to_coach: boolean;
  visible_to_parent: boolean;
  retrieved_chunk_ids: string[];
  created_at: string;
  expires_at: string | null;
  acted_at: string | null;
}

// ---------------------------------------------------------------------------
// Insert payload (fields auto-generated by DB are omitted)
// ---------------------------------------------------------------------------

export interface RecommendationInsert {
  athlete_id: string;
  rec_type: RecType;
  priority: RecPriority;
  title: string;
  body_short: string;
  body_long?: string | null;
  confidence_score: number;
  evidence_basis: Record<string, unknown>;
  trigger_event_id?: string | null;
  context: Record<string, unknown>;
  visible_to_athlete?: boolean;
  visible_to_coach?: boolean;
  visible_to_parent?: boolean;
  retrieved_chunk_ids?: string[];
  expires_at?: string | null;
}

// ---------------------------------------------------------------------------
// Query options
// ---------------------------------------------------------------------------

export interface GetRecommendationsOptions {
  role?: 'ATHLETE' | 'COACH' | 'PARENT';
  context?: string;
  recTypes?: RecType[];
  limit?: number;
  includeExpired?: boolean;
}
